# Generated by Django 3.2.9 on 2021-11-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='downvote',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='upvote',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
