# Generated by Django 3.2.9 on 2021-11-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211107_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='downvote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='upvote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
